// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	DeleteOrderItem(ctx context.Context, oiID uuid.UUID) error
	GetOrderItemList(ctx context.Context) ([]OrderItem, error)
	GetOrderItemsByOrderId(ctx context.Context, orderID uuid.UUID) (OrderItem, error)
	GetOrderList(ctx context.Context, userID uuid.UUID) ([]Order, error)
	UpdateOrderAddress(ctx context.Context, arg UpdateOrderAddressParams) (Order, error)
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
